### PR TITLE
 build.html: add openssl to the list of dependencies

### PR DESCRIPTION
**Pull request by GarciaLnk**
The OpenSSL toolkit binary is needed for avbtool to work properly, since it is called in multiple places in avbtool.py.

openssl1.1 contains only the libraries from the 1.1.1 version for compatibility reasons and should not be needed.

### CODE REVIEW

**Comment by SkewedZeppelin** [comment]
This needs special handling, I use an old fedora 36 openssl binary with the openssl1.1 libs for avbtool to work on 19.1 and higher.

**Comment by GarciaLnk** [comment]
Hm, I'm unsure why openssl1.1 would be needed on Fedora 36, nonetheless I still think openssl package should be added to the list to avoid errors in minimal images that don't contain the binary.

**Comment by SkewedZeppelin** [comment]
I have it noted somewhere, but one of the build scripts processes the output of an openssl dump command to get the key used to insert into the images and the output was changed after 1.1, which breaks it.

so openssl1.1 is necessary in path, it isn't fedora or distro specific

**Comment by SkewedZeppelin** [comment]
https://github.com/LineageOS/android_build/blob/lineage-20.0/tools/releasetools/sign_target_files_apks.py#L1029-L1037

**Pull request merged**
